config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'

  get 'home/about'

  get 'home/terms'

  resources :user
  resources :theme
  resources :posts
  resources :stars

  get 'theme/show/:id' => 'theme#show'

  root to: 'home#index'

  match 'toggle_star', :to => 'toggle_star#toggle_star', :via => [:get, :post]

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :theme
  has_many :stars, :dependent => :destroy
  validates_uniqueness_of :theme_id, :scope => :user_id
end

app/models/star.rb
class Star < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  validates_uniqueness_of :post_id, :scope => :current_user_id
end

app/models/theme.rb
class Theme < ActiveRecord::Base
  has_many :posts, :dependent => :destroy
  has_many :users, through: :posts
  default_scope { where('posted_at <= ?', Date.today) }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :posts, :dependent => :destroy
  has_many :themes, through: :posts
  has_many :stars, :dependent => :destroy
  attr_accessor :login

  def starable_for?(post)
    post && post.user != self && !stars.exists?(:post_id => post.id)
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:login]
  validates :username, presence: true, uniqueness: true

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["username = :value OR lower(email) = lower(:value)", { :value => login }]).first
    else
      where(conditions).first
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
      devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
      devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @themes = Theme.last
    @post = Post.new  #新規ポスト作成用
    @star = Star.new  #新規ファボ作成
  end

  def about
  end

  def terms
  end

  def new
    @themes = Theme.find(params[:id])
    @posts = @themes.posts
    @star = Star.new  #新規ファボ作成
    @posts.id = "id"
  end

  def create
    @star = Star.new(star_params)
    if @star.save
      redirect_to @star, notice: "ユーザ登録しました。"
    else
      render 'home#index'
    end
  end

  def update
    @star = Star.new(star_params)
    if @star.save
      redirect_to @star, notice: "ユーザ登録しました。"
    else
      render 'home#index'
    end
  end

  private
  def user_params
    params.require(:star).permit(:user_id, :post_id)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, :except => [:show, :index]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to :back, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to :back, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:theme_id, :user_id, :content, :posted_at)
    end
end

app/controllers/stars_controller.rb
class StarsController < ApplicationController

  before_filter :authenticate_user!, :except => [:show, :index]

  def index
    @themes = Theme.find(1)
  end

  def show
    @themes = Theme.find(1)
  end

  def new
    @themes = Theme.find(params[:id])
    @posts = @themes.posts
    @star = Star.new  #新規ファボ作成
  end

  def create
    @star = Star.new(star_params)
    if @star.save
      redirect_to :back, notice: "お気に入り登録完了"
    else
      render 'home#index'
    end
  end

  def destroy
    @star.destroy
  end

    private
    # Rails4からStrongParamaterと呼ばれる機能が追加されました。
    # セキュリティのため、permitメソッドで許可したパラメータ名しか取得できません。
    def star_params
      params.require(:star).permit(:user_id, :post_id, :current_user_id)
    end
end

app/controllers/theme_controller.rb
class ThemeController < ApplicationController
  def index
    @themes = Theme.all.reverse_order
  end

  def show
    @themes = Theme.find(params[:id])
    @posts = @themes.posts
    @post = Post.new  #新規ポスト作成用
    @star = Star.new  #新規ファボ作成
  end

  def new
    @themes = Theme.find(params[:id])
    @posts = @themes.posts
    @star = Star.new  #新規ファボ作成
    @posts.id = "id"
  end

  def create
    @star = Star.new(star_params)
    if @star.save
      redirect_to @star, notice: "ユーザ登録しました。"
    else
      render 'home#index'
    end
  end

  def update
    @star = Star.new(star_params)
    if @star.save
      redirect_to @star, notice: "ユーザ登録しました。"
    else
      render 'home#index'
    end
  end

  private
  def user_params
    params.require(:star).permit(:user_id, :post_id)
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  end

  def show
    @users = User.find(params[:id])
    @posts = @users.posts.order("id DESC")
    @star = Star.new  #新規ファボ作成
  end

  def create
    @star = Star.new(star_params)
    if @star.save
      redirect_to @star, notice: "ユーザ登録しました。"
    else
      render 'home#index'
    end
  end

  def update
    @star = Star.new(star_params)
    if @star.save
      redirect_to @star, notice: "ユーザ登録しました。"
    else
      render 'home#index'
    end
  end

  private
  def user_params
    params.require(:star).permit(:user_id, :post_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/star_helper.rb
module StarHelper
end

app/helpers/theme_helper.rb
module ThemeHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/about.html.erb
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p>

app/views/home/index.html.erb
<div class="wrapper">
  <div class="top">
  <div class="top_image">
    <img src="images/logo.jpg" class="logo">
    <p class="text1">１日ひとつ、考えるテーマを提供するメールマガジン。</p>
    <p class="text2">あなたの考えを保存し、様々な考えに触れるWebサイト。</p>
    <div class="start_wrap">
     <% if current_user == @users %>
    <p class="button_start"><a href="<%= new_user_registration_path %>" class="start">はじめる（無料）</a></p>
    <% end %>
    </div>
  </div>
  </div>

  <div class="sec1">
    <div class="sec1_wrapper">
      <!-- get the theme of the day -->
      <h1><%= @themes.name %></h1>
      <p class="posted_at"><%= @themes.posted_at %></p>


      <!-- post form the day -->
      <%= render partial: 'layouts/form' %>

      <ul class="sort">
        <li><a href="" >投稿順</a></li>
        <li> | </li>
        <li><a href="" >人気順</a></li>
      </ul>

      <!-- repeat 10 posts to the themes of the day -->
      <% @themes.posts.each do |post| %>
      <ul class="posts">
        <li>
          <ul class="like">
          <li>
          <%= link_to post.user.username, user_path(post.user) %>
          </li>
          <li>
            <%= form_for @star, :remote => true do |f| %>
            <%= f.hidden_field :post_id, value: post.id %>
            <%= f.hidden_field :user_id, value: post.user.id %>
              <% if current_user.present? %>
                <%= f.hidden_field :current_user_id, value: current_user.id %>
              <% end %>
              <%= image_submit_tag("like_button.png", class: 'img_fav') %>
          <% end %>
          </li>
          <li>
          <%= post.stars.count %>
          </li>
          </ul>
          <p class="content"><%= post.content %></p>
        </li>
      </ul>
      <% end %>
      <!-- end of the repeat -->
    </div>

  </div>
</div>

app/views/home/terms.html.erb
<h1>Home#terms</h1>
<p>Find me in app/views/home/terms.html.erb</p>

app/views/layouts/_fav.html.erb
    <%= form_for @star, :remote => true do |f| %>
    <%= f.hidden_field :post_id, value: post.id %>
    <%= f.hidden_field :user_id, value: post.user.id %>
    <% if current_user.present? %>
      <%= f.hidden_field :current_user_id, value: current_user.id %>
    <% end %>

     <%= image_submit_tag("like_button.png", class: 'img_fav') %>
     <% end %><%= post.stars.count %>

app/views/layouts/_form.html.erb
<script type="text/javascript">
$(document).ready(function(){
    $(".button_post").hide();
    var flg = "close";
    $(".field").click(function(){
        $(".button_post").fadeIn();
        if(flg == "close"){
          flg = "open";
        }
    });
});
</script>

<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.hidden_field :theme_id, value: @themes.id %>
    <% if current_user.present? %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <% end %>
  <div class="field">
    <%= f.text_area :content, :placeholder => "自分の考えを投稿する。" %>
  </div>
  <div class="button_post" id="hidden_post">
    <%= f.submit "POST", :class => 'post' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width,user-scalable=no,maximum-scale=1" />
  <title>Kainashi</title>
  <link href='http://fonts.googleapis.com/css?family=Nunito:300' rel='stylesheet' type='text/css'>
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header class="header_wrapper" id="headerWrapper">
  <div class="header">

    <a href= "/" class="logo"><img src="/" ></a>

    <div class="menu">
      <a href="#"><span>≡</span>MENU</a>
    </div>
    <div class="drawer">
    <nav>
    <ul class="nav">
      <li class="how_to"><a href="" class="link">HOW TO</a></li>
      <li class="titles"><a href="/theme" class="link">THEMES</a></li>
      <% if user_signed_in? %>
      <li class="login button_login"><a href="<%= user_path(current_user.id) %>" class="button_login"><%= current_user.username %></a>
          <ul class="hidden_list">
            <li><%= link_to 'マイページ', user_path(current_user.id), class: "hidden_link" %></li>
            <li><%= link_to 'プロフィール変更', edit_user_registration_path, class: "hidden_link" %></li>
            <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "hidden_link" %></li>
          </ul>
      </li>
      <% else %>
        <li class="login button_login"><a href="#" class="button_login">SIGN IN / LOGIN</a>
          <ul class="hidden_list">
            <li><%= link_to "サインアップ", new_user_registration_path, class: "hidden_link" %></li>
            <li><%= link_to "ログイン", new_user_session_path, class: "hidden_link" %></li>
          </ul>
        </li>
      <% end %>
    </ul>
    </nav>
    </div>
  </div>
  <script>
    window.addEventListener('load', function() {
    new FastClick(document.body);
    }, false);
    $('.menu').click(function(e){
      $('.nav').slideToggle();
      e.preventDefault();
    });
</script>
</header>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>Theme</th>
      <th>User</th>
      <th>Content</th>
      <th>Posted at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.theme_id %></td>
        <td><%= post.user_id %></td>
        <td><%= post.content %></td>
        <td><%= post.posted_at %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>


<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Theme:</strong>
  <%= @post.theme_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>Posted at:</strong>
  <%= @post.posted_at %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/sample_notifier/sample_mail.html.erb
<h1>SampleNotifier#sample_mail</h1>

<p>
  <%= @greeting %>, find me in app/views/sample_notifier/sample_mail.html.erb
</p>

app/views/sample_notifier/sample_mail.text.erb
SampleNotifier#sample_mail

<%= @greeting %>, find me in app/views/sample_notifier/sample_mail.text.erb

app/views/star/index.html.erb
<h1>Star#index</h1>
<p>Find me in app/views/star/index.html.erb</p>

<%= @themes.name %>
<%= @posts.content %>
<%= @users.username %>
<%= @stars.created_at %>

app/views/stars/index.html.erb
<h1>Star#index</h1>
<p>Find me in app/views/star/index.html.erb</p>

<%= @themes.name %>

app/views/theme/index.html.erb
  <div class="sec2">
    <div class="sec2_wrapper">
    <p class="page_title">THEMES</p>
    <!-- each do で繰り返す　-->
    <% @themes.each do |theme| %>
    <ul class="themes">
      <li>
        <div class="date_box">
        <p class="date"><%= theme.posted_at %></p><!--日付取得 -->
        </div>
        <div class="theme_box">
        <h1 class="theme"><%= link_to theme.name, theme_path(theme.id), class: "theme"%></h1>
        </div>
        <p class="post_number"><%= theme.posts.count %> POSTS</p>
      </li>
    </ul>
    <% end %>
    <!-- end of the repeat -->
  </div>
  </div>

app/views/theme/show.html.erb
  <div class="sec1">
    <div class="sec1_wrapper">
      <p class="page_title">THEME</p>
      <!-- get the theme of the day -->
      <h1><%= @themes.name %></h1>
      <p class="posted_at"><%= @themes.posted_at %></p><!--日付取得 -->

      <!-- post form the day -->
      <%= render partial: 'layouts/form' %>

      <ul class="sort">
        <li><a href="" >投稿順</a></li>
        <li>|</li>
        <li><a href="" >人気順</a></li>
      </ul>

      <!-- repeat 10 posts to the theme of the day -->
      <% @themes.posts.each do |post| %>
      <ul class="posts">
        <li>
          <ul class="like">
          <li>
          <%= link_to post.user.username, user_path(post.user) %>
          </li>
          <li>
            <%= form_for @star, :remote => true do |f| %>
            <%= f.hidden_field :post_id, value: post.id %>
            <%= f.hidden_field :user_id, value: post.user.id %>
              <% if current_user.present? %>
                <%= f.hidden_field :current_user_id, value: current_user.id %>
              <% end %>
              <%= image_submit_tag("like_button.png", class: 'img_fav') %>
          <% end %>
          </li>
          <li>
          <%= post.stars.count %>
          </li>
          </ul>
          <p class="content"><%= post.content %></p>
        </li>
      </ul>
      <% end %>
      <!-- end of the repeat -->
    </div>
  </div>
</div>

app/views/user/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>

app/views/user/show.html.erb
  <div class="sec4_wrapper">
    <% if current_user == @users %>
      <%= link_to 'アカウント管理', edit_user_registration_path, :class => 'manage' %>
    <% end %>
    <table>
       <tr>
         <th>POST</th>
         <th>LIKE</th>
       </tr>
       <tr>
         <td><%= @users.posts.count %></td>
         <td><%= @users.stars.count %></td>
       </tr>
     </table>
     <p class="username"><%= @users.username %></p>
     <p class="navi">さんのマイページ</p>
<ul class="posts">
<li class="each_post">
<% @posts.each do |post| %>
  <p class="title"><%= link_to post.theme.name, theme_path(post.theme) %></p>
  <div class="date_like">
  <span class="date"><%= post.updated_at %></span>
  <ul class="like">
    <li>
      <%= form_for @star, :remote => true do |f| %>
    </li>
    <li>
      <%= f.hidden_field :post_id, value: post.id %>
      <%= f.hidden_field :user_id, value: post.user.id %>
      <% if current_user.present? %>
      <%= f.hidden_field :current_user_id, value: current_user.id %>
      <% end %>
      <%= image_submit_tag("like_button.png", class: "img_fav") %>
      <% end %>
    </li>
    <li>
      <%= post.stars.count %>
    </li>
  </ul>
  </div>
  <div class="content_wrap">
    <p class="content"><%= post.content %></p>
  <% if current_user == @users %>
  <p class="edit">
    <%= link_to '編集', edit_post_path(post) %> |
    <%= link_to '削除', post, method: :delete, data: { confirm: 'Are you sure?' } %>
  </p>
  <% end %>
  </div>
<% end %>
</li>

</ul>
    </div>

  </div>
</div>
</div>